### ISSUE TITLE
[Feature request] remote dns request via proxy

### ISSUE THREAD

**Issue by cutemanworking** [IrineSistiana/mos-chinadns#10]
**Feature request**

通过socks5或http代理连接外面的dns服务器

软路由作为透明代理， 机器本身直连外面的dns服务器容易出问题，经过代理更稳健和可靠。软路由本身可以用routing方法通过隧道连接外面的dns服务器，但隧道容易出现单点的不可控故障，而代理软件一般都可实现HA。 所以现在只能在mos-chinadns上游再挂个dnscrypt-proxy

**Comment by IrineSistiana** [comment]
非常棒的建议。

已在`v1.1.0`中实现socks5代理。

暂不考虑实现http代理。

**Comment by widewind2015** [comment]
@cutemanworking ,如果设置 mos-chinadns 上游为自己搭建的dnscrypt-proxy，那么在mos-chinadns的server->remote:protocol 是否只能选择 udp？现在的socks5 还不支持认证，所以还不放心做开放的代理。

**Comment by cutemanworking** [comment]
1. remote:protocol可以选udp或tcp,  取决于dnscrypt-proxy的listen port协议是tcp还是udp.  理论上是udp更快些;
2. mos-chinadns运行的机器上或内网其它机器上建支持socks5的代理， mos-chinadns的代理指向它就好了。 留意， 如果你代理连接的远程机器如果用域名， 这域名要加在mos-chinadns的白名单里面，不然有可能出问题哟 ^-^

**Comment by widewind2015** [comment]
好的，测试了确实用 udp 快很多。期待 mos-chinadns 的 socks5 验证功能。之前直连一些公共doh server 很不稳定。

**Comment by IrineSistiana** [comment]
@widewind2015 为什么要 socks5 验证功能？建议开issue解释一下。
 
BTW，如果TCP启用连接复用，和UDP应该一样快。我记得dnscrypt-proxy好像支持tcp复用。

---

>留意， 如果你代理连接的远程机器如果用域名， 这域名要加在mos-chinadns的白名单里面，不然有可能出问题哟 ^-^

@cutemanworking 这个问题下个版本应该会处理。👍
