### ISSUE TITLE
大佬大佬，我把里面的IP换成了台湾中华电信的dns，可是还是无法访问是怎么回事呀？

### ISSUE THREAD

**Issue by chinaniupai** [IrineSistiana/mos-chinadns#12]
我把里面的IP换成了台湾中华电信的dns，可是还是无法访问是怎么回事呀？

**Comment by dwbclz** [comment]
本地能PING通那DNS不。。。

**Comment by dwbclz** [comment]
谢谢 Irine Sistiana 大佬的分享，敬 Made with love ♥。。。

**Comment by chinaniupai** [comment]
> 本地能PING通那DNS不。。。

咋办

**Comment by dwbclz** [comment]
找个PING得通的换上撒。。。

**Comment by chinaniupai** [comment]
> 找个PING得通的换上撒。。。

可是我不知道doh或者dot都有哪些比较好用的，除了谷歌跟这个cf的之外

**Comment by dwbclz** [comment]
俺这边的电信和移动线路用8.8.8.8的DOT还行，延迟大部分200多点。。。
路由，有时走日本，有时到美国，有时又直接就在香港。。。
其他的1.1.1.1，OPENDNS的也试过，兄弟参考下吧。。。

**Comment by chinaniupai** [comment]
> 俺这边的电信和移动线路用8.8.8.8的DOT还行，延迟大部分200多点。。。
> 路由，有时走日本，有时到美国，有时又直接就在香港。。。
> 其他的1.1.1.1，OPENDNS的也试过，兄弟参考下吧。。。

9.9.9.9的doh如何？

**Comment by dwbclz** [comment]
8.8.8.8，dot，name那里填dns.google

**Comment by chinaniupai** [comment]
@dwbclz 刚刚发现更新了，这个改怎么填写最好呢？
# 分流器设定
dispatcher:
    cache: # 缓存设定
        size: 512 # 缓存大小，单位: 条。0表示禁用缓存。如512表示最多缓存512条DNS应答。
        min_ttl: 300 # 最小生存时间。单位: 秒。
    max_concurrent_queries: 150 # 最大并发查询数。默认150。

**Comment by dwbclz** [comment]
俺设置的512。。。
参考至smart***的大佬，说它的缓存每条占用600字节。。。
所以，依据自己的期望内存占用大小设置吧。。。
路由器就根据自己的剩余内存大小，PC就设大点之类的。。。
mos最近越来越好用了。。。 Irine Sistiana大佬费心了！！！
俺最近也正准备把mos换到俺的ac86u原版固件上。前面用的smart***,因为它可以ipkg install smart***，直接就用在了，下载大师，optware环境，直接就开机启动啦，就不用啥梅林，啥官改，啥梅林改了。。。嘿嘿
