### ISSUE TITLE
建议ecs ip可以选择使用请求者ip[Feature request]

### ISSUE THREAD

**Issue by WoChen5770** [IrineSistiana/mos-chinadns#14]
**Feature request**

要添加什么功能？

**为什么**

该功能使用场景和好处。

**Comment by WoChen5770** [comment]
1 这样可以部署到服务器，2 不用担心电信会定时更换公网ip 。 可参考 overture项目

**Comment by IrineSistiana** [comment]
@WoChen5770 如果把 mos-chinadns 部署到公网，建议使用 unbound + mos-chinadns。unbound 负责插入请求者的ip，负责缓存之类的。mos-chinadns 则作为 unbound 的上游。

mos-chinadns 是个分流器，插ECS和缓存这方面做的没有unbound好。而且效率不高。

**Comment by IrineSistiana** [comment]
下一个版本可能会加入这个功能

**Comment by WoChen5770** [comment]
感谢回复。还是希望加入，这样不用部署两个服务，不然很麻烦。我说的overture也是分流，也可以缓存和自动ecs。
可以设置为 那两个ecs ip为空就拿请求者ip当作ecs。

**Comment by IrineSistiana** [comment]
> mos-chinadns 是个分流器，插ECS和缓存这方面做的没有unbound好。而且效率不高。

考虑了一下，没必要再造个方形的轮子，所以这个功能不会加入。

新版本加入了强制复写ECS的开关，可以更好的配合unbound。

感谢提出建议。
