### ISSUE TITLE
华硕路由器原生固件/梅林固件/Openwrt安装包

### ISSUE THREAD

**Issue by dwbclz** [IrineSistiana/mos-chinadns#15]
才发现scripts中有 openwrt 的脚本。那个，嘿嘿，厚颜请教 Irine Sistiana 大佬，得空时，能否支持下华硕路由器原生固件/梅林固件的自启动及相关iptable等等的脚本哇。。。参照smartdns。。。谢谢哇！

**为什么**
方便部署。。。

**Comment by wanwanxian** [comment]
支持加一

**Comment by vsxen** [comment]
搭车问一下 解析出这个 怎么还不能用？

```
;; ANSWER SECTION:
www.google.com.		156	IN	A	172.217.164.100

;; Query time: 1280 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
```

**Comment by dwbclz** [comment]
> 搭车问一下 解析出这个 怎么还不能用？
> 
> ```
> ;; ANSWER SECTION:
> www.google.com.		156	IN	A	172.217.164.100
> 
> ;; Query time: 1280 msec
> ;; SERVER: 127.0.0.1#53(127.0.0.1)
> ```

DNS能解析出正确地址只是第一步啊，后面还有封IP、TCP阻断、啥啥啥啊。。。

**Comment by vsxen** [comment]
> > 搭车问一下 解析出这个 怎么还不能用？
> > ```
> > ;; ANSWER SECTION:
> > www.google.com.		156	IN	A	172.217.164.100
> > 
> > ;; Query time: 1280 msec
> > ;; SERVER: 127.0.0.1#53(127.0.0.1)
> > ```
> 
> DNS能解析出正确地址只是第一步啊，后面还有封IP、TCP阻断、啥啥啥啊。。。

我以为解析出来的就是位被墙的ip   对墙还是不了解

[2020-07-09 20:43:44] connect to www.youtube.com:443
[2020-07-09 20:43:44] Socket connected to ss server: 
[2020-07-09 20:43:45] connect to www.youtube.com:443
[2020-07-09 20:43:45] Socket connected to ss server: 
[2020-07-09 20:43:46] connect to content-autofill.googleapis.com:443
[2020-07-09 20:43:46] Socket connected to ss server:

**Comment by shikkoku** [comment]
> > > 搭车问一下 解析出这个 怎么还不能用？
> > > ```
> > > ;; ANSWER SECTION:
> > > www.google.com.		156	IN	A	172.217.164.100
> > > 
> > > ;; Query time: 1280 msec
> > > ;; SERVER: 127.0.0.1#53(127.0.0.1)
> > > ```
> > 
> > 
> > DNS能解析出正确地址只是第一步啊，后面还有封IP、TCP阻断、啥啥啥啊。。。
> 
> 我以为解析出来的就是位被墙的ip 对墙还是不了解
> 
> [2020-07-09 20:43:44] connect to [www.youtube.com:443](http://www.youtube.com:443)
> [2020-07-09 20:43:44] Socket connected to ss server:
> [2020-07-09 20:43:45] connect to [www.youtube.com:443](http://www.youtube.com:443)
> [2020-07-09 20:43:45] Socket connected to ss server:
> [2020-07-09 20:43:46] connect to content-autofill.googleapis.com:443
> [2020-07-09 20:43:46] Socket connected to ss server:
GOOGLE的IP早被封禁得七七八八了，这不是DNS的问题，别老想着直连了。

倒是WIKI上好像没说在OpenWrt上使用需要把原来的的DNS端口设置成0，然后再启动mos-chinadns服务。或者更改配置默认的监听端口，然后使用dns转发功能实现。

**Comment by IrineSistiana** [comment]
@shikkoku 每个人的使用环境都不一样。Openwrt的碎片化也很严重。全都写进wiki不现实。

相信对于已经开始折腾dns的玩家来说，这些都是小问题。

**Comment by shikkoku** [comment]
> @shikkoku 每个人的使用环境都不一样。Openwrt的碎片化也很严重。全都写进wiki不现实。
> 
> 相信对于已经开始折腾dns的玩家来说，这些都是小问题。

之前没试过直接用53端口，通常是使用dns转发功能。但查资料说这样资源占用会高点。

**Comment by shikkoku** [comment]
root@OpenWrt:~# mos-chinadns -c config.yaml -dir2exe
INFO[0000] main: mos-chinadns ver: v1.2.0-0-g5e173f3
INFO[0000] main: arch: amd64 os: linux
INFO[0000] main: current working directory: /usr/bin
FATA[0000] main: can not load config file, open config.yaml: no such file or directory

文件路径是
/etc/mos-chinadns/config.yaml
/etc/mos-chinadns/chn.list
/etc/mos-chinadns/chn_domain.list

root@OpenWrt:~# mos-chinadns -c /etc/mos-chinadns/config.yaml -dir2exe
INFO[0000] main: mos-chinadns ver: v1.2.0-0-g5e173f3
INFO[0000] main: arch: amd64 os: linux
INFO[0000] main: current working directory: /usr/bin
FATA[0000] main: init dispatcher: loading ip policies, failed to load ip file from ./chn.list, open ./chn.list: no such file or directory

？？？

**Comment by IrineSistiana** [comment]
@shikkoku 工作路径错了。

可自行文件和列表不同文件夹， 配置文件里`xxx.list`写完整路径，不要省略。

**Comment by shikkoku** [comment]
> @shikkoku 工作路径错了。
> 
> 可自行文件和列表不同文件夹时， 配置文件里文件路径`xxx.list`要写完整路径，不要省略。
> 
> 要不然mos-chinadns不知道去哪里找。

mos-chinadns -c /etc/mos-chinadns/config.yaml -dir /etc/mos-chinadns/ 可以正常运行了。因为提供的openwrt的执行脚本写的是这个路径我就这样放了

将原配置文件中

`local:
        addr: "223.5.5.5:53" # 服务器地址。留空将禁用该服务器。
        protocol: "udp"`

的protocol: "udp"改成doh后解析网站失败

WARN[0002] exchangeDNS: local server failed after 16ms: doHTTP: http request failed: Get "https://223.5.5.5/dns-query?dns=AAABAAABAAAAAAAAA2VwNwZlYXRwaWcCY24AABwAAQ": read tcp 113.111.***.***:59004->223.5.5.5:53: read: connection reset by peer  id=7521 question="[{ep7.eatpig.cn. 28 1}]"

WARN[0037] query failed, context deadline exceeded

**Comment by IrineSistiana** [comment]
@shikkoku doh的端口是443。不是53。

**Comment by shikkoku** [comment]
> @shikkoku doh的端口是443。不是53。

变更dns类型是要把上边的端口号一并变更是吗，我试试。

**Comment by vsxen** [comment]
> > > > 搭车问一下 解析出这个 怎么还不能用？
> > > > ```
> > > > ;; ANSWER SECTION:
> > > > www.google.com.		156	IN	A	172.217.164.100
> > > > 
> > > > ;; Query time: 1280 msec
> > > > ;; SERVER: 127.0.0.1#53(127.0.0.1)
> > > > ```
> > > 
> > > 
> > > DNS能解析出正确地址只是第一步啊，后面还有封IP、TCP阻断、啥啥啥啊。。。
> > 
> > 
> > 我以为解析出来的就是位被墙的ip 对墙还是不了解
> > [2020-07-09 20:43:44] connect to [www.youtube.com:443](http://www.youtube.com:443)
> > [2020-07-09 20:43:44] Socket connected to ss server:
> > [2020-07-09 20:43:45] connect to [www.youtube.com:443](http://www.youtube.com:443)
> > [2020-07-09 20:43:45] Socket connected to ss server:
> > [2020-07-09 20:43:46] connect to content-autofill.googleapis.com:443
> > [2020-07-09 20:43:46] Socket connected to ss server:
> 
> GOOGLE的IP早被封禁得七七八八了，这不是DNS的问题，别老想着直连了。
> 
> 倒是WIKI上好像没说在OpenWrt上使用需要把原来的的DNS端口设置成0，然后再启动mos-chinadns服务。或者更改配置默认的监听端口，然后使用dns转发功能实现。

可是使用ss的话，看日志会转发DNS请求到ss server ，也就是设置了这个DNS server也没啥用？
