### ISSUE TITLE
[Feature request]希望发布Windows 32位版本

### ISSUE THREAD

**Issue by liuxb** [IrineSistiana/mos-chinadns#16]
**Feature request**

希望能发布Windows 32位版本，多谢啊。

**Comment by hang333** [comment]
试过自己 build 吗

**Comment by terrytw** [comment]
[main.zip](https://github.com/IrineSistiana/mos-chinadns/files/4908011/main.zip)
顺手编译了一个，你试试吧

**Comment by liuxb** [comment]
> 
> 
> [main.zip](https://github.com/IrineSistiana/mos-chinadns/files/4908011/main.zip)
> 顺手编译了一个，你试试吧

多谢，测试可用。
还是希望官方能出一个额。。。
