### ISSUE TITLE
[Feature request]是否有可能支持hosts

### ISSUE THREAD

**Issue by terrytw** [IrineSistiana/mos-chinadns#17]
**Feature request**

是否有可能支持hosts用来去广告

**为什么**

是不是性能比openwrt自带的dnsmasq要好？
因为wiki里写到性能很强大，忍不住好奇

**Comment by IrineSistiana** [comment]
不会。dnsmasq的host匹配性能也很强大。

**Comment by kagamir** [comment]
也就是说还得套一层dnsmasq吗

**Comment by terrytw** [comment]
> 也就是说还得套一层dnsmasq吗

你要是想用hosts的话必须要套的
不需要hosts就直接把dnsmasq端口设成0，让本软件监听53就可以了
