### ISSUE TITLE
[BUG] fatal error: concurrent map writes

### ISSUE THREAD

**Issue by dwbclz** [IrineSistiana/mos-chinadns#18]
time="2020-07-11T21:56:18+08:00" level=info msg="main: mos-chinadns ver: v1.2.0-0-g5e173f3"
time="2020-07-11T21:56:18+08:00" level=info msg="main: arch: arm64 os: linux"
time="2020-07-11T21:56:18+08:00" level=info msg="main: current working directory: /tmp/mnt/ASUS_ROUTER/script_bootloader/usr/mos-chinadns"
time="2020-07-11T21:56:18+08:00" level=info msg="newIPPolicies: ip list ./chn.list loaded, length 7189"
time="2020-07-11T21:56:19+08:00" level=info msg="newDomainPolicies: domain list ./chn_domain.list loaded, length 74917"
time="2020-07-11T21:56:19+08:00" level=info msg="initDispatcher: local server ECS enabled"
time="2020-07-11T21:56:19+08:00" level=info msg="initDispatcher: remote server ECS enabled"
time="2020-07-11T21:56:19+08:00" level=info msg="main: tcp server started"
time="2020-07-11T21:56:19+08:00" level=info msg="main: udp server started"
time="2020-07-11T22:03:29+08:00" level=warning msg="exchangeDNS: local server failed after 3003ms: read tcp 10.245.143.16:47977->223.5.5.5:853: i/o timeout" id=56902 question="[{9.9.4.4.7.c.6.8.3.7.c.0.9.1.6.b.6.f.3.5.2.8.4.0.b.0.8.8.9.0.4.2.ip6.arpa. 12 1}]"
time="2020-07-11T22:06:51+08:00" level=warning msg="query failed, context deadline exceeded" id=23733 question="[{stun.services.mozilla.com. 1 1}]"
time="2020-07-11T22:11:59+08:00" level=warning msg="query failed, context deadline exceeded" id=38329 question="[{ajax.cloudflare.com. 1 1}]"
time="2020-07-11T22:12:24+08:00" level=warning msg="query failed, context deadline exceeded" id=21368 question="[{www.google.com. 1 1}]"

......

time="2020-07-12T00:49:21+08:00" level=warning msg="exchangeDNS: remote server failed after 3460ms: read tcp 10.245.143.16:40413->8.8.8.8:853: i/o timeout" id=9921 question="[{settings-win.data.microsoft.com. 1 1}]"
time="2020-07-12T00:49:22+08:00" level=warning msg="query failed, context deadline exceeded" id=9921 question="[{settings-win.data.microsoft.com. 1 1}]"
time="2020-07-12T00:49:23+08:00" level=warning msg="exchangeDNS: remote server failed after 4463ms: read tcp 10.245.143.16:40415->8.8.8.8:853: i/o timeout" id=9921 question="[{settings-win.data.microsoft.com. 1 1}]"
fatal error: concurrent map writes

goroutine 6841 [running]:
runtime.throw(0x50e41f, 0x15)
	runtime/panic.go:1116 +0x54 fp=0x400003bcf0 sp=0x400003bcc0 pc=0x41fa4
runtime.mapdelete(0x476380, 0x4000114840, 0x400003bdb0)
	runtime/map.go:702 +0x3ec fp=0x400003bd50 sp=0x400003bcf0 pc=0x1e04c
github.com/IrineSistiana/mos-chinadns/dispatcher/cache.(*Cache).Get(0x4000114870, 0x400009cba0, 0x1f, 0x10001, 0x40003c2eb6, 0x0)
	github.com/IrineSistiana/mos-chinadns/dispatcher/cache/cache.go:78 +0x208 fp=0x400003bde0 sp=0x400003bd50 pc=0x37cb68
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).tryGetFromCache(0x40000f99d0, 0x40005197a0, 0x400053c8c0)
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:278 +0x7c fp=0x400003be20 sp=0x400003bde0 pc=0x3ad7cc
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).ServeDNS(0x40000f99d0, 0x5c70e0, 0x4000587560, 0x40005197a0, 0x0, 0x0, 0x0)
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:259 +0x138 fp=0x400003bea0 sp=0x400003be20 pc=0x3ad6b8
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).ListenAndServe.func2(0x40000f99d0, 0x40005197a0, 0x5ca5e0, 0x400000e028, 0x5c18a0, 0x4000114e40)
	github.com/IrineSistiana/mos-chinadns/dispatcher/server.go:133 +0xf4 fp=0x400003bfa0 sp=0x400003bea0 pc=0x3b5794
runtime.goexit()
	runtime/asm_arm64.s:1148 +0x4 fp=0x400003bfa0 sp=0x400003bfa0 pc=0x73984
created by github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).ListenAndServe
	github.com/IrineSistiana/mos-chinadns/dispatcher/server.go:126 +0x21c

goroutine 1 [chan receive, 175 minutes]:
main.main()
	github.com/IrineSistiana/mos-chinadns/main.go:181 +0x62c

goroutine 5 [IO wait, 175 minutes]:
internal/poll.runtime_pollWait(0x7fa3133f78, 0x72, 0x0)
	runtime/netpoll.go:203 +0x44
internal/poll.(*pollDesc).wait(0x40000fa318, 0x72, 0x0, 0x0, 0x5054ef)
	internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0x40000fa300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:384 +0x184
net.(*netFD).accept(0x40000fa300, 0x5c70a0, 0x40000a0058, 0x502cf2)
	net/fd_unix.go:238 +0x2c
net.(*TCPListener).accept(0x4000094440, 0x0, 0x0, 0x0)
	net/tcpsock_posix.go:139 +0x2c
net.(*TCPListener).Accept(0x4000094440, 0x3, 0x40000a0aa0, 0xe, 0x5c5de0)
	net/tcpsock.go:261 +0x5c
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).ListenAndServe(0x40000f99d0, 0x502cf2, 0x3, 0x40000a0aa0, 0xe, 0x5c8, 0x1, 0x4000038f80)
	github.com/IrineSistiana/mos-chinadns/dispatcher/server.go:46 +0x3b0
main.main.func2(0x502cf2, 0x3)
	github.com/IrineSistiana/mos-chinadns/main.go:158 +0xd4
created by main.main
	github.com/IrineSistiana/mos-chinadns/main.go:168 +0x54c

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7fa3133e98, 0x72, 0x0)
	runtime/netpoll.go:203 +0x44
internal/poll.(*pollDesc).wait(0x40000fa618, 0x72, 0x500, 0x5c8, 0x0)
	internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).ReadFrom(0x40000fa600, 0x4000164000, 0x5c8, 0x5c8, 0x0, 0x0, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:219 +0x140
net.(*netFD).readFrom(0x40000fa600, 0x4000164000, 0x5c8, 0x5c8, 0x30, 0x0, 0x0, 0x1, 0x4000990001)
	net/fd_unix.go:208 +0x44
net.(*UDPConn).readFrom(0x400000e028, 0x4000164000, 0x5c8, 0x5c8, 0x4000997dd8, 0x5c8, 0x703c0, 0x4000997e20)
	net/udpsock_posix.go:47 +0x44
net.(*UDPConn).ReadFrom(0x400000e028, 0x4000164000, 0x5c8, 0x5c8, 0x5ca5e0, 0x400000e028, 0x5c18a0, 0x4000114e70, 0x0)
	net/udpsock.go:118 +0x48
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).ListenAndServe(0x40000f99d0, 0x502cfb, 0x3, 0x40000a0aa0, 0xe, 0x5c8, 0x1, 0x0)
	github.com/IrineSistiana/mos-chinadns/dispatcher/server.go:102 +0x160
main.main.func2(0x502cfb, 0x3)
	github.com/IrineSistiana/mos-chinadns/main.go:158 +0xd4
created by main.main
	github.com/IrineSistiana/mos-chinadns/main.go:169 +0x574

goroutine 7 [syscall, 175 minutes]:
os/signal.signal_recv(0x0)
	runtime/sigqueue.go:147 +0xc4
os/signal.loop()
	os/signal/signal_unix.go:23 +0x20
created by os/signal.Notify.func1
	os/signal/signal.go:127 +0x44

goroutine 6843 [runnable]:
github.com/IrineSistiana/mos-chinadns/dispatcher.copyAndAppendECSIfNotExist(0x4000519cb0, 0x4000084d60, 0x4000264ef8)
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:481 +0x2cc
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).exchangeDNS.func1(0x40003ff030, 0x4000519cb0, 0x40000f99d0, 0x5c70e0, 0x400097b2c0, 0x40000f9dc0, 0x40000fc380, 0x8f2dc2211aa59f00, 0x40005132c0)
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:324 +0x4b4
created by github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).exchangeDNS
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:318 +0x42c

goroutine 6842 [select]:
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).exchangeDNS(0x40000f99d0, 0x5c70e0, 0x400097b2c0, 0x4000519cb0, 0x0, 0x0, 0x0)
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:420 +0x2b4
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).ServeDNS(0x40000f99d0, 0x5c70e0, 0x400097b2c0, 0x4000519cb0, 0x0, 0x0, 0x0)
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:265 +0xa8
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).ListenAndServe.func2(0x40000f99d0, 0x4000519cb0, 0x5ca5e0, 0x400000e028, 0x5c18a0, 0x4000114e70)
	github.com/IrineSistiana/mos-chinadns/dispatcher/server.go:133 +0xf4
created by github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).ListenAndServe
	github.com/IrineSistiana/mos-chinadns/dispatcher/server.go:126 +0x21c

goroutine 6844 [select]:
github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).exchangeDNS.func2(0x40003f0101, 0x40000f99d0, 0x40000fc380, 0x4000519cb0, 0x5c70e0, 0x400097b2c0, 0x40000f9dc0, 0x40005132c0, 0x40003ff030, 0x40002568c0, ...)
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:364 +0x50c
created by github.com/IrineSistiana/mos-chinadns/dispatcher.(*Dispatcher).exchangeDNS
	github.com/IrineSistiana/mos-chinadns/dispatcher/dispatcher.go:358 +0x22c

**Comment by IrineSistiana** [comment]
Please try `v1.2.2`.

**Comment by dwbclz** [comment]
Thank you IrineSistiana, I am trying 1.2.2. . .

**Comment by dwbclz** [comment]
The program has been running for 48 hours without any errors. Thank you IrineSistiana！
