### ISSUE TITLE
[BUG]大小写不一致导致编译失败

### ISSUE THREAD

**Issue by terrytw** [IrineSistiana/mos-chinadns#19]
**出现了什么问题**
试着自己编译了一下失败，提示
dispatcher/pool/request_logger.go:5:2: cannot find package "." in:
        /root/go/mos-chinadns/vendor/github.com/sirupsen/logrus

后来发现代码中sirupsen和实际路径名称Sirupsen大小写不一致造成的

**Comment by terrytw** [comment]
顺便建议一下，go交叉编译还是比较快的，能否考虑一下发布的时候直接多加几个平台的二进制文件

**Comment by IrineSistiana** [comment]
这不是bug。编译需要 go 1.14 并且 启用 go module。

没发布的平台使用率都小于3%。

需要编译不常用的平台可以直接划掉`release.py`里的注释，然后运行。`python3 release.py`
