### ISSUE TITLE
(Bug)LocalServerPEMCA为空，caPath2Pool必须要求证书，无法使用系统证书

### ISSUE THREAD

**Issue by xiangyu123** [IrineSistiana/mos-chinadns#2]
```
{
    "bind_addr": "127.0.0.1:53", 
    "local_server": "223.5.5.5:53",    
    "local_server_url": "https://223.5.5.5/dns-query",
    "local_server_pem_ca": "",
    "local_server_block_unusual_type": false,  
    "remote_server": "8.8.8.8:443", 
    "remote_server_url": "https://dns.google/dns-query",  
    "remote_server_pem_ca": ""
}
```

https://github.com/IrineSistiana/mos-chinadns/blob/7df77848b2e3dbd9d1a3a794c2907d465d166f2c/dispatcher.go#L113-L115

https://github.com/IrineSistiana/mos-chinadns/blob/7df77848b2e3dbd9d1a3a794c2907d465d166f2c/dispatcher.go#L569-L582

如果config.json里面local_server配置使用DoH, 本来此类证书是默认的标准CA，使用系统的证书池就好，local_server_pem_ca无需配置，但是程序仍然要求配置一个本地CA证书。且本地CA不配置或者配置错误后，无法使用系统证书池。 这算是个bug吧

@IrineSistiana

**Comment by IrineSistiana** [comment]
@xiangyu123  Please try https://github.com/IrineSistiana/mos-chinadns/commit/7df77848b2e3dbd9d1a3a794c2907d465d166f2c
