### ISSUE TITLE
国内 IP 地址列表

### ISSUE THREAD

**Issue by dwbclz** [IrineSistiana/mos-chinadns#20]
今天，在V2EX上，看见了大佬们关于国内IP地址的一些讨论。。。
IrineSistiana 大佬看看能做个参考不。。。
https://www.v2ex.com/t/689263

**Comment by IrineSistiana** [comment]
mos-chinadns默认是域名+IP分流，如果域名不在列表里就会IP分流，再加上cname检查，加上ecs，分流很少出错。我一直用APNIC的IP，没觉得不准。因为除非某域名不在域名列表里并且大陆和国外都存在服务器并且国外用了乱广播的IP并且国内DNS出错了没响应或者返回了它的国外IP，才会导致分流出错。这种情况基本上不存在。

没有完美的IP地址表。IP地址表不准没有关系。好在格式都一样，mos-chinadns也都支持。所以留给用户选择吧。我就不推荐了。

**Comment by dwbclz** [comment]
谢谢IrineSistiana大的耐心回复~确实，没有完美的列表啊。。。
v1.2.2挂着的这两天。没见到有啥错误提示，稳得很！
