### ISSUE TITLE
[Feature request]将日志输出至文件

### ISSUE THREAD

**Issue by snylonue** [IrineSistiana/mos-chinadns#25]
**Feature request**

添加将日志输出至文件的选项

**为什么**

便于查找日志，排查错误，避免不在终端中运行时丢失日志
(可能已经有这个功能了，但是 wiki 里没看见)

**Comment by IrineSistiana** [comment]
目前没有。

日志输出到了stderr。一般情况下启动mos-chinadns的守护进程会将stderr转到文件。

**Comment by Neverends4** [comment]
如果用systemd且version高于236，可以在mos service文件加入：
`[Service]
StandardError=append:/var/log/moserror.log`
然后执行下面该的命令，注意替换你自己的mos服务名
`systemctl daemon-reload&&systemctl restart mos`
log示例
[``](https://sm.ms/image/cqUyNI2lekWPTGb)

**Comment by p0we7** [comment]
> StandardError=append:/var/log/moserror.log

你的 systemd 配置是怎样的写的? 我写的配置搞了很久都运行不到 , 查看 journalctl 日志也看不到 mos-chinadns 的输出.

我的配置
```
[Unit]
Description=mos-chinadns
After=network.target 
StartLimitBurst=0
StartLimitIntervalSec=60

[Service]
#Type=simple
Restart=on-failure
RestartSec=10
ExecStart=/root/mos-chinadns/mos-chinadns -c /root/mos-chinadns/config.yaml -dir2exe
StandardError=append:/root/mos-chinadns/error.log

[Install]
WantedBy=multi-user.target
Alias=mos-chinadns.service
```
