### ISSUE TITLE
远端和近端DNS解析顺序是什么

### ISSUE THREAD

**Issue by muziling** [IrineSistiana/mos-chinadns#26]
近端DNS有ip policy可配，远端这参数不支持吗？
解析请求是同时发出到近端和远端吗？ 如果远端DNS是在香港之类的机房，可能会比近端DNS先返回解析结果。

**Comment by IrineSistiana** [comment]
> 近端DNS有ip policy可配，远端这参数不支持吗？

不支持，如果`remote`返回的结果一定会被接受。

> 如果远端DNS是在香港之类的机房，可能会比近端DNS先返回解析结果。

    domain_policies: "force:./chn_domain.list"

会强制`chn_domain.list`中的域名仅`local`解析。

或者考虑`remote.delay_start`手动给`remote`加一点延时。

**Comment by IrineSistiana** [comment]
新版本已不再适用
