### ISSUE TITLE
[Proposal]将mos-chinadns包装成coredns的插件

### ISSUE THREAD

**Issue by IrineSistiana** [IrineSistiana/mos-chinadns#30]
mos-chinadns功能不多。

将分流与上游部分包装成coredns的第三方插件。依托coredns大量的插件，只需一个程序coredns，就能实现更多很复杂的功能。

需注意：配置难度会大幅上升。需自己组装插件，编译，设置coredns。

计划插件包将只以源码的形式提供给专业用户。mos-chinadns的release和设置方式不会改变。

**Comment by lostz** [comment]
同意,现在有分支吗?大家一起参与.

**Comment by IrineSistiana** [comment]
@lostz 想了想还是放弃了。

整合成一个代价太高了。而且远没有同时开coredns和mos-chinadns方便。

**Comment by IceCodeNew** [comment]
现在是重新打算拾起这个提案了么？
https://github.com/IrineSistiana/mos-chinadns/commit/494fc1a06f005732b86b724b3a8bca4ade4a98e9

**Comment by IrineSistiana** [comment]
@IceCodeNew 没。

打算从头造轮子。
