### ISSUE TITLE
监听地址设置与分流/局域网内查询的问题

### ISSUE THREAD

**Issue by leon911000** [IrineSistiana/mos-chinadns#31]
监听地址设置为127.0.0.1:53的时候本机[::1]和192.168.1.2（路由器192.168.1.1）不能查询～然后监听地址设为0.0.0.0:53后本机上述3个都能查询了，但局域网内手机wlan指定192.168.1.2为DNS的话就会出现“已连接 但无法访问互联网”问题，访问网页提示err_name_not_resolved～再然后监听地址设为192.168.1.2:53的话，局域网内手机正常，本机v4查询127.0.0.1和v6查询[::1]又No response from server了...........

有没啥能兼顾v4、v6和局域网其他设备的解法呢？

**Comment by IrineSistiana** [comment]
没太看明白。mos-chinadns放在哪了？地址多少，手机地址多少？

**Comment by IrineSistiana** [comment]
哦。监听多端口多地址。

已经在搞了。几天后下个版本会有。
