### ISSUE TITLE
[Feature request]增加直接暴露Local/Remote服务器端口的功能

### ISSUE THREAD

**Issue by Neverends4** [IrineSistiana/mos-chinadns#32]
**Feature request**

**要添加什么功能？**
直接暴露Local/Remote服务器端口给本地，譬如在config.yaml里添加下述配置
`bind: ["udp://127.0.0.1:53","udp://127.0.0.1:5353"-"Remote"]`
表示监听udp 53，使用分流，监听udp 5353，不使用分流直接走Remote服务器解析

**为什么**

在路由器或类似环境下，方便其他程序在特定情况下直接调用DOT/DOH服务器，而不用考虑分流带来的延时/IP域名有效性，同时又不必禁用mos的分流。目前可以通过多开mos，监听多个端口来曲线实现此功能，但感觉有点高射炮打蚊子。

另外可以考虑增加多个Remote服务器，方便特殊用途，譬如多个VPS代理走不同DNS解析的情况。

**Comment by IrineSistiana** [comment]
> 直接暴露Local/Remote服务器端口给本地  

其实直连dot/h没必要多开mos。可以考虑多开AdguardTeam/dnsproxy。加到mos里感觉问题反而变的复杂了。

> 另外可以考虑增加多个Remote服务器，方便特殊用途，譬如多个VPS代理走不同DNS解析的情况。

可以试试 v1.4.0。
