### ISSUE TITLE
[Feature request] release里增加armv5的包

### ISSUE THREAD

**Issue by brainos233** [IrineSistiana/mos-chinadns#33]
**Feature request**

增加armv5平台

**为什么**

无论是自己编译的armv7和armv6的以及release里的二进制文件都无法在我的华硕rt-ac1900p上运行，显示`Illegal instruction`，即使该路由器的架构是armv7l，经测试只有armv5的文件能运行。

附上路由器的uname -a输出内容
`Linux RT-AC1900P-CB70 2.6.36.4brcmarm #1 SMP PREEMPT Sun Jun 28 14:07:12 EDT 2020 armv7l ASUSWRT-Merlin`

**Comment by brainos233** [comment]
补充一点，在AdGuardHome上也有同样的问题，怀疑是go编译器的问题

**Comment by KirbyKFC** [comment]
[](https://golang.org/doc/install/source#environment)
>$GOARM (for arm only; default is auto-detected if building on the target processor, 6 if not)
>This sets the ARM floating point co-processor architecture version the run-time should target. If you are compiling on the target system, its value will be auto-detected.
>
> - GOARM=5: use software floating point; when CPU doesn't have VFP co-processor
> - GOARM=6: use VFPv1 only; default if cross compiling; usually ARM11 or better cores (VFPv2 or better is also supported)
> - GOARM=7: use VFPv3; usually Cortex-A cores  
>
>If in doubt, leave this variable unset, and adjust it if required when you first run the Go executable. The GoARM page on the Go >community wiki contains further details regarding Go's ARM support.

```
cat /proc/cpuinfo

Processor       : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 1795.68
Features        : swp half thumb fastmult edsp
```
与GO编译器有关，我手上的armv7l的CPU不支持VFP，所以只有armv5的能运行。你的大概也是这个原因。
