### ISSUE TITLE
[BUG]1.3.1  mos-chinadns-linux-mipsle-softfloat.zip 二进制文件有问题

### ISSUE THREAD

**Issue by richardxyz** [IrineSistiana/mos-chinadns#34]
首先，感谢您热心的反馈问题。

在提交问题之前，请确认1)问题在最新版本中也会出现。2)问题不是由于服务器无法连接(网络问题或服务器设置问题)导致的。

缺少信息和不符合要求的issus可能会被无视。

---

**出现了什么问题**
1.3.1 版本的release文件mos-chinadns-linux-mipsle-softfloat.zip 二进制文件有问题

描述一下问题的表现。并附上log或截图。
上传此版本到路由器，运行时无任何输出，程序也不报错不退出。参数不带配置文件也不报错。
上一版本无此问题
利用最新源代码编译出的二进制文件无此问题。

**如何重现**

描述一下什么情况下出现了该问题。请尽可能的包含：

- 运行在什么系统
- 使用的配置文件
- 使用的启动参数
- 做了什么导致问题出现

**Comment by IrineSistiana** [comment]
emmmm.... 

release里的二进制文件跟从源码编译出的唯一区别就是用upx压缩过。

1.3.1我用了的新的upx 3.96(1.2用的是upx3.95)。所以怀疑是upx的问题。

我手上没有mipsle的设备，所以暂时没法测试。

**Comment by richardxyz** [comment]
我本机编译使用的upx版本是3.95

**Comment by IrineSistiana** [comment]
回退了。

如果方便这个bug可以给upx提一下。
