### ISSUE TITLE
1.4.1 版本无法解析部分域名，比如 bbs.vcb-s.com

### ISSUE THREAD

**Issue by feise** [IrineSistiana/mos-chinadns#38]
感谢您热心的反馈Bug。您的描述越详细越有助于定位和解决Bug。

---

**出现了什么问题**

一些域名无法正确解析，导致无法打开，比如 bbs.vcb-s.com ，1.4.1版本解析失败，1.3.1版本解析成功

![微信截图_20200821142000](https://user-images.githubusercontent.com/20085557/90858953-cd3cf300-e3b9-11ea-8143-ec65c535dd92.png)

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

使用系统 win 10 LTSC 17763.1793
使用默认的配置文件，已尝试彻底删除后重新安装使用，依旧出现问题。

[err_log.log](https://github.com/IrineSistiana/mos-chinadns/files/5107160/err_log.log)

**Comment by IrineSistiana** [comment]
emmm.....默认配置文件有一项设的不合理。

在第86行，把`domain`的设置填上`"accept:./chn_domain.list"`

**Comment by feise** [comment]
> emmm.....默认配置文件有一项设的不合理。
> 
> 在第86行，把`domain`的设置填上`"accept:./chn_domain.list"`

thanks，加上以后可以正常解析了
