### ISSUE TITLE
[BUG]1.4.0 默认配置文件，国内网站解析时间稍长，部分解析不了

### ISSUE THREAD

**Issue by adolink** [IrineSistiana/mos-chinadns#39]
感谢您热心的反馈Bug。您的描述越详细越有助于定位和解决Bug。

---

国内网站解析时间稍长，部分解析不了

描述一下问题的表现。可以直接附上log或截图。
nslookup解析某泥潭两个地址
nslookup bbs.nga.cn
时间约有几秒卡顿，但能解析
mos-chinadns显示
WARN[0382] listenAndServeUDP 127.0.0.1:53: query failed: all upstreams failed or not respond in time  id=3625 question="[{bbs.nga.cn. 28 1}]"

nslookup bbs.ngacn.cc
;; connection timed out; no servers could be reached
mos-chinadns显示
WARN[0524] listenAndServeUDP 127.0.0.1:53: query failed: all upstreams failed or not respond in time  id=18267 question="[{bbs.ngacn.cc. 1 1}]"

使用1.3.1版及默认配置文件是正常的。
外网地址解析也是正常的。

描述一下如何重现该问题。请尽可能的包含：

- 运行在什么系统
OpenWrt 19.07.2 -x86-64
- 使用的配置文件
默认配置文件
- 使用的启动参数
- 使用场景等相关的信息

**Comment by IrineSistiana** [comment]
和 #38 一样。默认配置文件有点问题。 已更新。
