### ISSUE TITLE
自动配置ECS

### ISSUE THREAD

**Issue by thb007** [IrineSistiana/mos-chinadns#4]
比如开启ecs支持remote_ecs_subnet:"yes",不用手动的添加ecs的IP段，这样太麻烦了，如果能像Unbound那样全自动的多好。

**Comment by xiangyu123** [comment]
最好是可选的，自动识别还是手动填入

**Comment by IrineSistiana** [comment]
> 如果能像Unbound那样全自动的多好。

@thb007 我完全找不到相关的信息。能提供个链接或手册之类的么？我看看它是怎么自动的。

**Comment by IrineSistiana** [comment]
mos-chinadns的设计思路是`一个简单的分流器`，实现太多功能不太妥当。

如果有软件可以实现`自动配置ECS`功能，可以把mos-chinadns当作其上游服务器，mos-chinadns对已包含ECS的请求会如实转发不会修改其ECS部分。

所以`自动配置ECS`这个功能可能不会加入。

**Comment by thb007** [comment]
> > 如果能像Unbound那样自动的多好。
> 
> @ thb007我完全找不到相关的信息。能提供个链接或手册之类的么？我看看它是怎么自动的。

auto-trust-anchor-file: "/usr/local/etc/unbound/trust/root.key"
    
    # ECS support
    client-subnet-zone: "." 
    client-subnet-always-forward: yes
    max-client-subnet-ipv4: 24
    max-client-subnet-ipv6: 48

**Comment by IrineSistiana** [comment]
@thb007 看Unbound手册的意思是：`把客户端的地址自动附在ecs里`

外网用的Unbound是没有问题的，客户ip：1.2.3.4，附在ecs里没有问题。
但局域网或本机用Unbound：客户ip会是：192.*.*.*,或者127.0.0.1，附在ecs里没用。

只是猜测，没有验证。

**Comment by thb007** [comment]
> @thb007 看Unbound手册的意思是：`把客户端的地址自动附在ecs里`
> 
> 外网用的Unbound是没有问题的，客户ip：1.2.3.4，附在ecs里没有问题。
> 但局域网或本机用Unbound：客户ip会是：192._._.*,或者127.0.0.1，附在ecs里没用。
> 
> 只是猜测，没有验证。

我目前是用dnsdist均衡，上游为unbound，也是可以传递ecs，不一定公网ip
