### ISSUE TITLE
err in yaml config format 

### ISSUE THREAD

**Issue by cutemanworking** [IrineSistiana/mos-chinadns#41]
**出现了什么问题**

启动时不成功，一直报level=fatal msg="main: can not load config file, yaml: line 4: did not find expected key"。 
左看右看没觉得第四行有什么问题

**如何重现**

我的配置如下: 
dispatcher:
    bind: [ "udp://0.0.0.0:53","tcp://0.0.0.0:53" ]
upstream:
    local:
        addr: "223.5.5.5:443" 
        protocol: "doh" 
            idle_timeout: 10 
        doh:
            url: "https://223.5.5.5/dns-query" 
        deduplicate: false
        max_concurrent_queries: 0 
        policies:
            deny_unhandlable_types: false
            domain: "accept:./chn_domain.list|accept:./joey_domain.list|accept:./apple.list|deny:./reject.list|deny_all"
            deny_error_rcode: true
            check_cname: true
            deny_empty_ip_reply: true
            ip: "accept:./chn.list|deny_all"
        edns0:
            client_subnet: ""
            overwrite_ecs: false
    remote:
        addr: "1.0.0.1:853"
        protocol: "dot"
        socks5: "127.0.0.1:1099"
        tcp:
            idle_timeout: 10
        dot:
            server_name: "cloudflare-dns.com"
            idle_timeout: 10
        deduplicate: false
        max_concurrent_queries: 0
        policies:
            deny_unhandlable_types: false
            domain: "deny:./chn_domain.list" 
            deny_error_rcode: false
            check_cname: false
            deny_empty_ip_reply: false
            ip: ""
        edns0:
            client_subnet: ""
            overwrite_ecs: false
ca:
    path: []

**Comment by IrineSistiana** [comment]
配置文件是有层级的。缩进不可省略。

**Comment by cutemanworking** [comment]
我有缩进的， 刚粘贴时没注意 。 

![image](https://user-images.githubusercontent.com/20323985/91177139-df01fb80-e715-11ea-9f0b-524504c3fd05.png)

**Comment by IrineSistiana** [comment]
第7行多了。

(p.s. vscode装个yaml插件很容易就能找到错误格式

**Comment by cutemanworking** [comment]
是的。 我也刚逐行测试找出来了。 感谢!!!
