### ISSUE TITLE
提个疑惑和问题

### ISSUE THREAD

**Issue by chinaniupai** [IrineSistiana/mos-chinadns#42]
最新版本，请问看了一下配置文件，支持ipv6了，也就是::1，那么问题来了，我的疑惑就是ipv6用的是哪个服务器？用的ipv4的服务器？

**Comment by IrineSistiana** [comment]
`upstream`配置了哪些服务器就会用哪些服务器。

DNS服务器不存在`只能处理ipv4或ipv6的服务器`。所谓`ipv4或ipv6的服务器`只是指其服务器地址是ipv4还是ipv6。其实本身都是一个服务器。
