### ISSUE TITLE
openwrt重启network或者重新拨号后，无法正常连接至DoH服务器。

### ISSUE THREAD

**Issue by wonpn** [IrineSistiana/mos-chinadns#44]
openwrt x86平台
重启network，或者重新拨号。mos-chinadns不能正常解析。日志如下：

> DEBU[0171] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:30204  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> DEBU[0171] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:30204  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> DEBU[0172] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:44395  id=55224 question="[{www.bing.com. 1 1}]"
> DEBU[0172] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:44395  id=55224 question="[{www.bing.com. 1 1}]"
> DEBU[0173] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:44395  id=55224 question="[{www.bing.com. 1 1}]"
> DEBU[0175] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:44395  id=55224 question="[{www.bing.com. 1 1}]"
> DEBU[0175] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:51944  id=13521 question="[{tracker.ai.xiaomi.com. 28 1}]"
> DEBU[0175] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:49723  id=29219 question="[{tracker.ai.xiaomi.com. 1 1}]"
> DEBU[0175] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:40643  id=1369 question="[{relay-dcm.ai.xiaomi.com. 1 1}]"
> WARN[0176] listenAndServeUDP 127.0.0.1:5300: query failed: context deadline exceeded  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> DEBU[0176] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:30204  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> WARN[0176] listenAndServeUDP 127.0.0.1:5300: query failed: context deadline exceeded  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> WARN[0177] listenAndServeUDP 127.0.0.1:5300: query failed: context deadline exceeded  id=55224 question="[{www.bing.com. 1 1}]"
> WARN[0177] listenAndServeUDP 127.0.0.1:5300: query failed: context deadline exceeded  id=55224 question="[{www.bing.com. 1 1}]"
> WARN[0178] listenAndServeUDP 127.0.0.1:5300: query failed: context deadline exceeded  id=55224 question="[{www.bing.com. 1 1}]"
> DEBU[0179] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:44395  id=55224 question="[{www.bing.com. 1 1}]"
> INFO[0180] printStatus: HeapObjects: 14040 NumGC: 7 PauseTotalNs: 1160120, NumGoroutine: 44
> WARN[0180] listenAndServeUDP 127.0.0.1:5300: query failed: context deadline exceeded  id=55224 question="[{www.bing.com. 1 1}]"
> WARN[0180] listenAndServeUDP 127.0.0.1:5300: query failed: context deadline exceeded  id=13521 question="[{tracker.ai.xiaomi.com. 28 1}]"
> DEBU[0180] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:51944  id=13521 question="[{tracker.ai.xiaomi.com. 28 1}]"
> DEBU[0180] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:49723  id=29219 question="[{tracker.ai.xiaomi.com. 1 1}]"
> WARN[0180] listenAndServeUDP 127.0.0.1:5300: query failed: context deadline exceeded  id=29219 question="[{tracker.ai.xiaomi.com. 1 1}]"
> DEBU[0180] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:40643  id=1369 question="[{relay-dcm.ai.xiaomi.com. 1 1}]"
> WARN[0180] listenAndServeUDP 127.0.0.1:5300: query failed: context deadline exceeded  id=1369 question="[{relay-dcm.ai.xiaomi.com. 1 1}]"
> WARN[0181] dispatch: upstream local err after 10000ms: doHTTP: http request failed: Get "https://223.5.5.5/dns-query?dns=AAABAAABAAAAAAAAAjgxAzI0MQMxMTcDMTA2B2luLWFkZHIEYXJwYQAADAAB": context deadline exceeded,  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> WARN[0181] dispatch: upstream remote err after 10000ms: doHTTP: http request failed: Get "https://1.0.0.1/dns-query?dns=AAABAAABAAAAAAAAAjgxAzI0MQMxMTcDMTA2B2luLWFkZHIEYXJwYQAADAAB": context deadline exceeded,  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> WARN[0181] listenAndServeUDP 127.0.0.1:5300: query failed: context deadline exceeded  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> DEBU[0181] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:30204  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> WARN[0181] dispatch: upstream remote err after 10000ms: doHTTP: http request failed: Get "https://1.0.0.1/dns-query?dns=AAABAAABAAAAAAAAAjgxAzI0MQMxMTcDMTA2B2luLWFkZHIEYXJwYQAADAAB": context deadline exceeded,  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> WARN[0181] dispatch: upstream local err after 10000ms: doHTTP: http request failed: Get "https://223.5.5.5/dns-query?dns=AAABAAABAAAAAAAAAjgxAzI0MQMxMTcDMTA2B2luLWFkZHIEYXJwYQAADAAB": context deadline exceeded,  id=12633 question="[{81.241.117.106.in-addr.arpa. 12 1}]"
> DEBU[0181] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:50607  id=13613 question="[{edge-chat.instagram.com. 1 1}]"
> WARN[0182] dispatch: upstream remote err after 10000ms: doHTTP: http request failed: Get "https://1.0.0.1/dns-query?dns=AAABAAABAAAAAAAAA3d3dwRiaW5nA2NvbQAAAQAB": context deadline exceeded,  id=55224 question="[{www.bing.com. 1 1}]"
> DEBU[0182] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:50607  id=13613 question="[{edge-chat.instagram.com. 1 1}]"
> WARN[0182] dispatch: upstream remote err after 10000ms: doHTTP: http request failed: Get "https://1.0.0.1/dns-query?dns=AAABAAABAAAAAAAAA3d3dwRiaW5nA2NvbQAAAQAB": context deadline exceeded,  id=55224 question="[{www.bing.com. 1 1}]"
> DEBU[0183] listenAndServeUDP 127.0.0.1:5300: new query from 127.0.0.1:50607  id=13613 question="[{edge-chat.instagram.com. 1 1}]"
> WARN[0183] dispatch: upstream remote err after 10000ms: doHTTP: http request failed: Get "https://1.0.0.1/dns-query?dns=AAABAAABAAAAAAAAA3d3dwRiaW5nA2NvbQAAAQAB": context deadline exceeded,  id=55224 question="[{www.bing.com. 1 1}]"
> 

必须要重启mos-chinadns才能正常使用。这是什么原因，望解答

**Comment by wonpn** [comment]
mos-chinsdns监听的是5300端口，dnsmasq转发请求致5300端口。

另外问一下，我记得之前的版本由dns缓存功能，可以设置ttl的。是新版本取消了吗？

**Comment by IrineSistiana** [comment]
> 另外问一下，我记得之前的版本由dns缓存功能，可以设置ttl的。是新版本取消了吗？

缓存和ttl都去掉了。因为mos-chinadns基本上都是配合其他DNS服务器用，比如dnsmasq。其他DNS服务器都自带这些功能。能设置的方面更全，执行效率还高。

---

这个问题比较玄学....

试试换其他协议network重启后能正常连接么？

**Comment by IrineSistiana** [comment]
另一位用户已在MIPS平台复现。表现为：openwrt重启network或者重新拨号后，DoH服务器就再也无法解析(应该是因为无法连接）。

其他协议均不受影响。初步怀疑是Golang的HTTP库的问题。

复现率100%，建议OpenWrt用户先使用DoT协议。
