### ISSUE TITLE
请问为什么最新版本是测试版呀？

### ISSUE THREAD

**Issue by chinaniupai** [IrineSistiana/mos-chinadns#45]
请问为什么最新版本是测试版呀？这个版本是有什么未修复的已知问题吗？还是有什么问题呀？

**Comment by chinaniupai** [comment]
还有就是，8.8.8.8的doh也用不了，ISP为联通。

**Comment by chinaniupai** [comment]
有没有台湾地区的可以用doh的dns呀？

**Comment by IrineSistiana** [comment]
> 还有就是，8.8.8.8的doh也用不了，ISP为联通。

建议了解以下服务器设置里的`sock5`设置项。

**Comment by chinaniupai** [comment]
> sock5

sock5不是代理服务器吗？8.8.8.8的doh必须用代理吗？可是我没有呀
