### ISSUE TITLE
请问未在国内或者国外的文件里的IP或者域名，是走哪个DNS呢？

### ISSUE THREAD

**Issue by chinaniupai** [IrineSistiana/mos-chinadns#47]
请问未在国内或者国外的文件（chn和chn_domain.list）里的IP或者域名，是走哪个DNS呢？8.8.8.8的还是223.5.5.5.5的？

**Comment by chinaniupai** [comment]
如何让未在文件里的域名和IP强制走8.8.8.8呢？

**Comment by IrineSistiana** [comment]
@chinaniupai 如果是默认的配置。都走`google`了。

> 此软件DNS查询中的等待项目就会越来越多

应该是服务器速度太慢。建议换一个或者善于`sock5`设置。

**Comment by chinaniupai** [comment]
> @chinaniupai如果是默认的配置。都走`google`了。
> 
> > 此软件DNS查询中的等待项目就会越来越多
> 
> 应该是8.8.8.8服务器速度太慢。建议换一个或者善于服务器设置里的`socks5`设置项。

我也想善用`socks5`设置项，可是我没有梯子呀
