### ISSUE TITLE
[BUG] 官方使用的 APNIC CN CIDR 会有问题

### ISSUE THREAD

**Issue by rampageX** [IrineSistiana/mos-chinadns#48]
---

**出现了什么问题**

最近 www.google.com 有时会被解析到 "103.56.16.112 / 103.200.30.245 / 118.184.26.113" 这种地址, 用 QQWry 查询归属地为:

> 103.56.16.112 [亚太地区]  103.200.30.245 [亚太地区]  118.184.26.113 [香港 安畅网络(亚太)有限公司沙田数据中心(沙田火炭黃竹洋街8号新鴻基物流中心3楼)]

用 17mon 的查询为:

> 103.56.16.112 [中国 香港] 103.200.30.245 [中国 香港] 118.184.26.113 [中国 香港]

排查中发现我最近的改动是用了 mos-chinadns Wiki 脚本来更新 IP列表: chn.list , 通过用 `grepcidr` 查询这些地址包含在 APNIC 的 CN CIDR 中. 我之前使用的数据是 17mon 提供的 (https://github.com/17mon/china_ip_list), 并没有这个问题.

实际上我常用的数据是下面几个结合然后用 `cidrmerge` 合并后得到的:

```
https://cdn.jsdelivr.net/gh/firehol/blocklist-ipsets/ipip_country/ipip_country_cn.netset \
https://cdn.jsdelivr.net/gh/17mon/china_ip_list/china_ip_list.txt \
https://cdn.jsdelivr.net/gh/misakaio/chnroutes2/chnroutes.txt \
http://ipverse.net/ipblocks/data/countries/cn.zone"
```

这样得到的数据,也并不包含之前那几个 IP.

所以作者是否考虑改一下 CN IP 段的数据源?

**Comment by IrineSistiana** [comment]
感谢反馈，这个问题真的很大。

> 最近 www.google.com 有时会被解析到 "103.56.16.112 / 103.200.30.245 / 118.184.26.113" 

不仅仅这种解析到APNIC IP灰色地带无法防污染。现在部分运营商也会对特定域名进行劫持，解析到`127.0.0.1`或自己的黑洞IP。使用其他 CN IP 段也不能防污染。

用 CN IP 段防污染是基于一个假设：GFW的污染IP一定是国外的。这个假设很合理(GFW这么多年确实一直这么干)但也很脆弱(GFW完全可以不这样做)。

我觉得也许新增一个`gfw_domain.list`能更好的解决这个问题是🤔？

**Comment by rampageX** [comment]
gfw_domain.list 有个比较难处理的问题，就是例如： `google.com` 与 `dl.google.com` 这样的：
gfwlist 列表中一般会包含 google.com，这样会涵盖 dl.google.com，而实际上 dl.google.com 是有国内加速 IP 的。
apple 的域名也有类似情况。

当然如果在逻辑上优先目前的 chn_domain.list 可以避免这个问题。

**Comment by IrineSistiana** [comment]
`chn_domain.list`目前没包含[dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list)的中国google和apple域名。这些应该也加到`chn_domain.list`。

然后 `accept:./chn_domain.list|deny:./gfw_domain.list` 应该能达到理想效果。

**Comment by rampageX** [comment]
> `chn_domain.list`目前没包含[dnsmasq-china-list](https://github.com/felixonmars/dnsmasq-china-list)的中国google和apple域名。这些应该也加到`chn_domain.list`。
> 
> 然后 `accept:./chn_domain.list|deny:./gfw_domain.list` 应该能达到理想效果。

我试试,先关闭了.

**Comment by IrineSistiana** [comment]
不，还是开着吧。

自带的默认分流配置现在看起来有点问题。我考虑考虑怎么改。

**Comment by rampageX** [comment]
其实有一个不用任何列表的思路, 不知道作者是否有兴趣做到程序里.

1. 电信线路下: 向一个境外非 DNS 服务器查询某域名的 MX 记录, 如果立刻返回结果, 则被查询的域名被污染. 查询正常域名会超时.

```
dig +nocookie +short +tries=1 +time=1 wsj.com MX @example.com
199.59.149.204

dig +nocookie +short +tries=1 +time=1 163.com MX @example.com
;; connection timed out; no servers could be reached
```

2.移动线路下: 向一个境外非 DNS 服务器查询某域名的 MX 记录, 如果返回头信息中包含 `status: SERVFAIL`, 则被查询的域名被污染. 查询正常域名返回 `status: NOERROR`.

```
dig +nocookie +tries=1 +time=1 t66y.com MX @example.com

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> +nocookie +tries=1 +time=1 t66y.com MX @example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 25686
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

dig +nocookie +tries=1 +time=1 msn.com MX @example.com

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> +nocookie +tries=1 +time=1 msn.com MX @example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47015
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 5, ADDITIONAL: 13
```

3. 联通线路据说是和电信一样, 没条件, 未测试.

由于 GFW 采取抢答, 所以返回测试结果是很快的. 

我们假设 mos-chinadns 允许开启新的 自动模式. 在此模式下, 境内ISP服务器组, 境外安全服务器组并行查询, 正常情况下取境内服务器查询结果, 如果程序判断到域名被污染, 则取境外服务器结果.

**Comment by IrineSistiana** [comment]
@rampageX 感谢建议。

这个方式我考虑过了(而且尝试实现了)，并不是很好用。

因为

- GFW 并不是100%都抢答
- 电信&联通线路的抢答包源自 GFW，仅对黑名单内域名进行抢答。移动的抢答包其实不是抢答，而是移动已经把所有udp:53流量全部劫持到自己服务器了。(已抓包验证过)

所以程序不能有效的判断域名有没有被污染。

举个例子，在电信网络下，请求一个被污染的域名，GFW没有抢答，使程序判断域名无污染，然后取境内ISP服务器结果，就会导致污染。

还有延时差等问题.....

**Comment by rampageX** [comment]
@IrineSistiana 也是, 难啊...

**Comment by IrineSistiana** [comment]
v2fly维护了一个域名库，里面有常见的非CN域名。提取出来可以当本地服务器的黑名单。[non_chn_domain.list](https://github.com/IrineSistiana/mos-ip-doamin-data/blob/master/non_chn_domain.list)

比gfwlist干净，全。

**Comment by rampageX** [comment]
@IrineSistiana 它那些域名库我觉得把事情搞复杂了，是，可以细分，但是的确是复杂了。

目前我觉得只要 CN CIDR 足够准确，按照非安全组解析出来的 IP 不在 CN 范围就用安全组来解析，这样的逻辑已经很好用了。国内的 CDN 有保障，国外的话，用 SOCKS5 + 带 ECS 的国外服务器（google, twnic, quad9(11)等）也可以保障。

列表多了不是好事，个人意见。

**Comment by IrineSistiana** [comment]
只要 CN IP 足够准确就能放污染，现在已经不行了。

> 用 CN IP 段防污染是基于一个假设：GFW的污染IP一定是国外的。

> 现在部分运营商也会对特定域名进行劫持，解析到127.0.0.1或自己的黑洞IP。

> 移动的抢答包其实不是抢答，而是移动已经把所有udp:53流量全部劫持到自己服务器了。(已抓包验证过)

没错就是移动，现在移动自己有一套污染地址，是移动自己的黑洞IP。所以`污染IP一定是国外的`这个假设已经不成立了。

所以还需要一个黑名单。里面包含常见(包括被污染)的境外域名。

v2fly那个域名库我只打算用里面的`!cn`分类。

域名只是辅助，对已知位置的域名分流。剩下的域名还是靠CN IP分流。

到最后只有三个列表。境内/外域名和CN IP。境内域名表其实可加可不加，但有这么一个强大的域名表不加白不加。

---

完全支持geosite和geoip是因为我打算换v2fly的route模块进行IP/域名匹配。这样程序里的匹配逻辑我就可以不管了。顺便支持了geosite和geoip，用户也可以不去其他地方更新域名IP列表了。不是说那些域名都要用上......
