### ISSUE TITLE
[Feature request]提个小想法

### ISSUE THREAD

**Issue by chinaniupai** [IrineSistiana/mos-chinadns#49]
**Feature request**

可以将转发的域名被看到

**为什么**

这样的话有些软件的DNS查询如果失败。可以知道软件的DNS查询的网址和IP是国内还是国外的IP，

**Comment by chinaniupai** [comment]
像xxnet的那种浏览器形式的显示或者cmd形式的显示？就是打开之后直接一条一条的实时显示查询分流的DNS网址或者DNS的IP

**Comment by IrineSistiana** [comment]
加`-debug`启动会输出详细日志。就是比较乱，但能看出哪个请求进了哪个上游最后哪个应答被接受了。

**Comment by chinaniupai** [comment]
关于之前说添加socks5的问题，我输入了socks5: "127.0.0.1:8087"，但是为什么好像没起作用？我用的是xxnet
