### ISSUE TITLE
ECS能否根据访问者的ip自动识别

### ISSUE THREAD

**Issue by thb007** [IrineSistiana/mos-chinadns#5]
"remote_ecs_subnet": "1.2.3.0/24"   此处应该可以根据访问者的ip自动识别。毕竟每次切换网络这个ip端就会发生改变。

**Comment by IrineSistiana** [comment]
请详细描述一下相关使用场景和实现该功能的优势。

**Comment by thb007** [comment]
> 请详细描述一下相关使用场景和实现该功能的优势。谢谢
例子这个地址：https://i.233py.com/dns-query?name=baidu.com全自动附带ecs支持。

![%$ G)$LHY@DZ~38XT)4WUM](https://user-images.githubusercontent.com/17548936/79067078-9c53ff80-7cef-11ea-90bb-0cb929cb241d.png)

**Comment by IrineSistiana** [comment]
@thb007 这是应答里附带了ecs。不是请求。

而且可能没遵守 [rfc7871 page-13 7.2.2](https://tools.ietf.org/html/rfc7871#page-13) ：如果请求里没有ecs，应答里也必需没有。

你是打算将mos-chinadns用作公用服务器?

**Comment by thb007** [comment]
> @thb007 这是应答里附带了ecs。不是请求。
> 
> 而且可能没遵守 [rfc7871 7.2.2](https://tools.ietf.org/html/rfc7871#section-7.2.2) ：如果请求里没有ecs，应答里也必需没有。
> 
> 你是打算将mos-chinadns用作公用服务器? 请再详细描述使用场景。

我打算用mos-chinadns作DOH/DOT的分流，

**Comment by IrineSistiana** [comment]
mos-chinadns 是用作client。

作为Intermediate Nameserver，考虑用unbound,比如 client->unbound->mos-chinadns->.... 模式。
