### ISSUE TITLE
[BUG] dnsleaktest.com 测试有问题

### ISSUE THREAD

**Issue by Neverends4** [IrineSistiana/mos-chinadns#52]
感谢您热心的反馈Bug。您的描述越详细越有助于定位和解决Bug。

---

**出现了什么问题**

设置2个上游，默认alidns doh直连，google dns代理访问，仅针对gfw列表内的域名进行解析，但chrome直连访问dnsleaktest.com 结果里却有google的dns查询：
![dddd.png](https://i.loli.net/2020/10/10/WbZRdCXAacTjtxV.png)

**如何重现**

描述一下如何重现该问题。请尽可能的包含：

- 运行在什么系统
Windows 10 x64 1909---chinadns 1.5.2
- 使用的配置文件

dispatcher:
    bind: [ "udp://127.0.0.1:53","tcp://127.0.0.1:53","udp://[::1]:53","tcp://[::1]:53" ]
    max_udp_size: 1280 # 最大UDP负载大小。
upstream:
    local:
        server: "aliyun" # 使用的服务器的tag。该tag必需在server中定义。
        policies:
            query: # 请求策略。
                unhandlable_types: "accept"
               domain: "deny:./gfw.txt|deny:./b.txt"
            reply: # 应答策略
                error_rcode: "deny"
                cname: ""
                without_ip: "deny"
                ip: ""
    remote: # 另外一个上游，tag为`remote`。
        server: "google"
        policies:
            query:
                unhandlable_types: "accept"
                domain: "accept:./gfw.txt|accept:./b.txt"
            reply:
                error_rcode: "accept"
                cname: ""
                without_ip: "accept"
                ip: ""
server:
    aliyun:
        addr: "223.5.5.5:443" # 服务器地址。
        protocol: "doh" # 服务器协议。`tcp`|`udp`|`doh`|`dot`其中之一。
        socks5: "" # socks5代理服务器地址。注意: 不支持有密码验证的socks5服务器。udp协议不会使用socks5代理。
        deduplicate: false
        edns0:
            client_subnet:
                ipv4: ""
                ipv6: ""
            overwrite_ecs: false # 是否强制改写下游请求已有的ECS。
        tcp:
            idle_timeout: 10 # 空连接超时时间。单位: 秒。0表示禁用连接重用。
        dot:
            server_name: "dns.alidns.com" # [必需] 服务器的域名/证书名。
            idle_timeout: 10 # 空连接超时时间。单位: 秒。0表示禁用连接重用。
        doh:
            url: "https://223.5.5.5/dns-query" # [必需] DoH的URL。
    google:
        addr: "8.8.8.8:443"
        protocol: "doh"
        socks5: "127.0.0.1:51077"
        deduplicate: false
        edns0:
            client_subnet:
                ipv4: ""
                ipv6: ""
            overwrite_ecs: false
        tcp:
            idle_timeout: 10
        dot:
            server_name: "dns.google"
            idle_timeout: 10
        doh:
            url: "https://dns.google/dns-query"
ca:
    path: [ ]

- 使用的启动参数
使用service_control.bat启动

请问是配置文件不对？

**Comment by IrineSistiana** [comment]
按照你的配置，不再那两个列表里的域名，对于`local`和`remote`是竞争关系，谁先返回结果就接受谁的结果。

如果aliyun解析速度没8888快就会出现这种情况。

wiki里有其他配置方式能避免这个问题。

**Comment by IrineSistiana** [comment]
其实没有必要避免这个问题。因为dnsleaktest.com是国外域名所以aliyun就会比8888慢(大概率)。

国内域名不存在这个问题。
