### ISSUE TITLE
关于按域名+链式按IP分流的配置疑问

### ISSUE THREAD

**Issue by douglas-lee** [IrineSistiana/mos-chinadns#54]
看到wiki里的域名+链式混合配置，其中remote的一项是domain: "accept:/etc/gfwlist.txt|deny"，那是不是意味着，如果local server转给remote的请求，如果不在gfwlist.txt里就会被拒绝？如果这样的话，会存在一个逻辑问题吧？如果一个域名既不在chnlist和gfwlist里，且ip也恰好不在chnroute里，那是不是意味着不返回任何结果了？

**Comment by IrineSistiana** [comment]
并不会，redirect_xxxx会转发请求给服务器xxxx然后无条件接受。跟remote配置用没用xxxx没关系。
