### ISSUE TITLE
新功能的v2ray geoip在配置文件中如何配置？

### ISSUE THREAD

**Issue by douglas-lee** [IrineSistiana/mos-chinadns#55]
翻阅了config.yaml和最新的wiki，貌似关于这一部分如何配置没有更新？这个与原有gfwlist.txt的方式相比，有何优势？性能更好？还是只是为了用v2ray更完善的生态而已？

**Comment by douglas-lee** [comment]
另，希望作者考虑增加一个功能，即解析出来的地址支持增加到ipset，比如，可以指定，国内的域名解析出来以后将ip添加到ipset里名叫chnroute的，而国外的则添加到usroute的ipset list里，ipset的分组名称在配置文件里配置。因为在某些使用场景下，如果不配合ipset，就算解析出来的ip是国内，iptables的路由还是走了国外，目前用dnsmasq+ipset来强行解决这个问题，如果mos-chinadns能支持ipset就完美了。

**Comment by IrineSistiana** [comment]
> 貌似关于这一部分如何配置没有更新？

跟v2ray一模一样, `文件名:标签`, config.yaml提了.

https://github.com/IrineSistiana/mos-chinadns/blob/23cc313b5522e34a0420123074f0c360808286bb/config.yaml#L49-L51

> 原有方式相比

就是为了生态. wiki最后提性能区别了.

---

ipset在openwrt上确实很有用. 下个版本可能会加.

**Comment by douglas-lee** [comment]
好的，谢谢作者。另，建议考虑增加一个功能，比如google dns可以对外开放一个专门的解析端口，比如：5300，下面这个场景可能会需要用到：需要对不同的域名走不同的线路解析，比如日本，美国，香港，那么就会有4个DNS，阿里，走日本代理的DNS，走美国代理的DNS，走香港代理的DNS，然后，netflix需要走香港代理解析，facebook走美国解析，再打上不同的ipset标记，由路由分配走不同的线路。不知这样描述清晰否？目前这个方案，我是用dnsmasq+iptable+ipset实现的，如果能整合进mos-chinadns就太赞了。

**Comment by IrineSistiana** [comment]
> 比如google dns可以对外开放一个专门的解析端口，比如：5300，

不是很明白为什么什么做。如果某个下游不需要分流的话，可以独立运行一个小doh客户端，比如dnsproxy。

---

mos-chinadns支持ipset的方式会和dnsmasq差不多。匹配域名->加入对应的ipset表。

**Comment by douglas-lee** [comment]
嗯，就是给一些不需要分流的机器单独使用，目前是用的类似于dnsproxy来实现，只是能整合的话，不是少部署一个东西吗？哈哈哈
