### ISSUE TITLE
[Feature request] 禁止某些查询类型

### ISSUE THREAD

**Issue by rampageX** [IrineSistiana/mos-chinadns#60]
感谢您热心的提出建议。在提交建议前，请知晓mos-chinadns主要功能是分流，原则只添加和分流有关的功能。

---

**Feature request**

要添加什么功能？

程序可以设置禁止某些查询类型，比如ANY， AAAA 和最近 iOS 14 带来的 HTTPS (type65)

**Comment by IrineSistiana** [comment]
感觉这功能不常用。精细化过滤可以考虑套一个 coredns。
