### ISSUE TITLE
[Issue] 功能和配置上的疑问

### ISSUE THREAD

**Issue by HueLiu** [IrineSistiana/mos-chinadns#7]
**出现了什么问题**
测试环境：OpenWrt lean R20.4.8，
内核版本：4.19.115

1. mos-chinadns 新版本的缓存机制是否还是基于 Dnsmasq 的缓存大小设置？
2. 我了解到新版本采用 yaml 格式的配置。我想确认一下当前版本是否可以实现多 DNS？打个比方，例如 local (remote) 是否设置一个 main作为主DNS服务器，一个DNS服务器作为 fallback 备用。

**Comment by IrineSistiana** [comment]
1. mos-chinadns 从来没有过的缓存。所以不是很懂这个问题。
2. local/remote只有一个服务器，没有fallback。但如果local没有响应(离线，失败或者丢包等)，使remote的应答先到达，会使用remote的应答，作为fallback。(前提是启用了remote)

**Comment by HueLiu** [comment]
> 
> 
>     1. mos-chinadns 从来没有过的缓存。所以不是很懂这个问题。
> 
>     2. local/remote只有一个服务器，没有fallback。但如果local没有响应(离线，失败或者丢包等)，使remote的应答先到达，会使用remote的应答，作为fallback。(前提是启用了remote)

好的感谢
