### ISSUE TITLE
[BUG]1.0.1 Linux-amd64版本在openwrt 19.7.2运行几秒钟后报错panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by adolink** [IrineSistiana/mos-chinadns#9]
**出现了什么问题**

之前使用1.00rc3版本按照wiki方法安装使用成功。升级到1.0.1后启动服务几秒钟内进程就挂掉了，使用命令启动后报错如下

root@OpenWrt:~# mos-chinadns -dir /etc/mos-chinadns/ -c /etc/mos-chinadns/config
.yaml
INFO[0000] main: mos-chinadns ver: v1.0.1-0-g26fa0c7
INFO[0000] main: arch: amd64 os: linux
INFO[0000] main: current working directory: /etc/mos-chinadns/
INFO[0000] newIPPolicies: ip list ./chn.list loaded, length 10367
INFO[0000] newDomainPolicies: domain list ./chn_domain.list loaded, length 75522
INFO[0000] main: udp server started
INFO[0000] main: tcp server started
WARN[0007] exchange: ioErr: netErr.Timeout: read tcp 106.87.29.133:45534->1.0.0.1:853: i/o timeout  fromUDP="192.168.1.206:58958" id=1 question="[{1.1.168.192.in-addr.arpa. 12 1}]"
WARN[0026] exchange: ioErr: netErr.Timeout: read tcp 106.87.29.133:45540->1.0.0.1:853: i/o timeout  fromUDP="[fd5e:1b22:9b2b:0:95d2:2229:46db:622e]:52532" id=23824 question="[{youtube-ui.l.google.com. 28 1}]"
WARN[0027] exchange: ioErr: netErr.Timeout: read tcp 106.87.29.133:45544->1.0.0.1:853: i/o timeout  fromUDP="[fd5e:1b22:9b2b:0:95d2:2229:46db:622e]:61317" id=36570 question="[{fonts.googleapis.com. 28 1}]"
WARN[0027] exchange: ioErr: netErr.Timeout: read tcp 106.87.29.133:45544->1.0.0.1:853: i/o timeout  fromUDP="[fd5e:1b22:9b2b:0:95d2:2229:46db:622e]:51814" id=34527 question="[{fonts.googleapis.com. 1 1}]"
WARN[0027] exchange: ioErr: netErr.Timeout: read tcp 106.87.29.133:45544->1.0.0.1:853: i/o timeout  fromUDP="[fd5e:1b22:9b2b:0:95d2:2229:46db:622e]:64163" id=53115 question="[{fonts.googleapis.com. 28 1}]"
WARN[0027] exchange: ioErr: netErr.Timeout: read tcp 106.87.29.133:45544->1.0.0.1:853: i/o timeout  fromUDP="[fd5e:1b22:9b2b:0:95d2:2229:46db:622e]:55228" id=10863 question="[{pki-goog.l.google.com. 1 1}]"
WARN[0028] exchange: ioErr: netErr.Timeout: read tcp 106.87.29.133:45544->1.0.0.1:853: i/o timeout  fromUDP="[fd5e:1b22:9b2b:0:95d2:2229:46db:622e]:64010" id=49180 question="[{gstaticadssl.l.google.com. 1 1}]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7bb6ed]

goroutine 241 [running]:
main.newUpstream.func2(0x920920, 0xc0000a6150, 0xc35e80, 0x23, 0x40, 0x23, 0x0)
        github.com/IrineSistiana/mos-chinadns/upstream.go:77 +0x4d
main.(*upstreamCommon).exchange(0xc00012ab70, 0x91c640, 0xc0006123c0, 0xc0004110c0, 0x23, 0x40, 0xc000618e70, 0x0, 0x0, 0x0, ...)
        github.com/IrineSistiana/mos-chinadns/upstream.go:235 +0x697
main.(*upstreamCommon).Exchange(0xc00012ab70, 0x91c640, 0xc0006123c0, 0xc0004110c0, 0x23, 0x40, 0xc000618e70, 0x1, 0xc00024b790, 0x7bb0df, ...)
        github.com/IrineSistiana/mos-chinadns/upstream.go:157 +0xb8
main.(*dispatcher).queryUpstream(0xc0000a87e0, 0x91c640, 0xc0006123c0, 0xc00006f8c0, 0xc0004110c0, 0x23, 0x40, 0x915da0, 0xc00012ab70, 0x0, ...)
        github.com/IrineSistiana/mos-chinadns/dispatcher.go:469 +0xe0
main.(*dispatcher).queryLocal(0xc0000a87e0, 0x91c640, 0xc0006123c0, 0xc00006f8c0, 0xc0004110c0, 0x23, 0x40, 0xc000618e70, 0xc00002e800, 0xc00024b750, ...)
        github.com/IrineSistiana/mos-chinadns/dispatcher.go:473 +0xa8
main.(*dispatcher).serveRawDNS.func1(0xc0008c9a50, 0xc0000a87e0, 0x91c640, 0xc0006123c0, 0xc00006f8c0, 0xc0004110c0, 0x23, 0x40, 0xc000618e70, 0xc000610d80, ...)
        github.com/IrineSistiana/mos-chinadns/dispatcher.go:353 +0xdb
created by main.(*dispatcher).serveRawDNS
        github.com/IrineSistiana/mos-chinadns/dispatcher.go:351 +0x7b3

*其他问题*
1.0.1 linux_amd64下载后默认的config-example.yaml中远程服务的dot下的server_name: 里的"https://cloudflare-dns.com/dns-query" 应该是和doh下的 url: 里的"cloudflare-dns.com"写反了。直接用默认配置无法运行，内容互换后可以运行。

**Comment by IrineSistiana** [comment]
感谢反馈，问题已确认。

请尝试`v1.0.2`。

**Comment by adolink** [comment]
1.0.2连几秒钟都没撑过直接挂了

root@OpenWrt:~# mos-chinadns -dir /etc/mos-chinadns/ -c /etc/mos-chinadns/config
.yaml
INFO[0000] main: mos-chinadns ver: v1.0.2-0-gd6ac296
INFO[0000] main: arch: amd64 os: linux
INFO[0000] main: current working directory: /etc/mos-chinadns/
INFO[0000] newIPPolicies: ip list ./chn.list loaded, length 10367
INFO[0000] newDomainPolicies: domain list ./chn_domain.list loaded, length 75522
INFO[0000] main: udp server started
INFO[0000] main: tcp server started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7b6812]

goroutine 21 [running]:
main.(*upstreamCommon).exchange(0xc000128b70, 0x91c660, 0xc000450080, 0xc00044c100, 0x20, 0x20, 0xc00044e0e0, 0xc000038500, 0x0, 0x0, ...)
        github.com/IrineSistiana/mos-chinadns/upstream.go:242 +0x6f2
main.(*upstreamCommon).Exchange(0xc000128b70, 0x91c660, 0xc000450080, 0xc00044c100, 0x20, 0x20, 0xc00044e0e0, 0x0, 0xc000038790, 0x7bb18a, ...)
        github.com/IrineSistiana/mos-chinadns/upstream.go:156 +0xb8
main.(*dispatcher).queryUpstream(0xc0000a68a0, 0x91c660, 0xc000450080, 0xc00047a000, 0xc00044c100, 0x20, 0x20, 0x915dc0, 0xc000128b70, 0x0, ...)
        github.com/IrineSistiana/mos-chinadns/dispatcher.go:469 +0xe0
main.(*dispatcher).queryLocal(0xc0000a68a0, 0x91c660, 0xc000450080, 0xc00047a000, 0xc00044c100, 0x20, 0x20, 0xc00044e0e0, 0x6a1262, 0xc0000b76c0, ...)
        github.com/IrineSistiana/mos-chinadns/dispatcher.go:473 +0xa8
main.(*dispatcher).serveRawDNS.func1(0xc0004420b0, 0xc0000a68a0, 0x91c660, 0xc000450080, 0xc00047a000, 0xc00044c100, 0x20, 0x20, 0xc00044e0e0, 0xc00047c0c0, ...)
        github.com/IrineSistiana/mos-chinadns/dispatcher.go:353 +0xdb
created by main.(*dispatcher).serveRawDNS
        github.com/IrineSistiana/mos-chinadns/dispatcher.go:351 +0x7b3
root@OpenWrt:~# panic: runtime error: invalid memory address or nil pointer dere
ference
-ash: panic:: not found
root@OpenWrt:~# [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7
b6812]
-ash: [signal: not found
root@OpenWrt:~#
root@OpenWrt:~# goroutine 21 [running]:
-ash: goroutine: not found
root@OpenWrt:~# main.(*upstreamCommon).exchange(0xc000128b70, 0x91c660, 0xc00045
0080, 0xc00044c100, 0x20, 0x20, 0xc00044e0e0, 0xc000038500, 0x0, 0x0, ...)
-ash: syntax error: unexpected word (expecting ")")
-ash: syntax error: unexpected ")"
root@OpenWrt:~#         github.com/IrineSistiana/mos-chinadns/upstream.go:242 +0
x6f2
-ash: github.com/IrineSistiana/mos-chinadns/upstream.go:242: not found
root@OpenWrt:~# main.(*upstreamCommon).Exchange(0xc000128b70, 0x91c660, 0xc00045
0080, 0xc00044c100, 0x20, 0x20, 0xc00044e0e0, 0x0, 0xc000038790, 0x7bb18a, ...)
-ash: syntax error: unexpected word (expecting ")")
-ash: syntax error: unexpected ")"
root@OpenWrt:~#         github.com/IrineSistiana/mos-chinadns/upstream.go:156 +0
xb8
-ash: github.com/IrineSistiana/mos-chinadns/upstream.go:156: not found
root@OpenWrt:~# main.(*dispatcher).queryUpstream(0xc0000a68a0, 0x91c660, 0xc0004
50080, 0xc00047a000, 0xc00044c100, 0x20, 0x20, 0x915dc0, 0xc000128b70, 0x0, ...)
-ash: syntax error: unexpected word (expecting ")")
-ash: syntax error: unexpected ")"
root@OpenWrt:~#         github.com/IrineSistiana/mos-chinadns/dispatcher.go:469
+0xe0
-ash: github.com/IrineSistiana/mos-chinadns/dispatcher.go:469: not found
root@OpenWrt:~# main.(*dispatcher).queryLocal(0xc0000a68a0, 0x91c660, 0xc0004500
80, 0xc00047a000, 0xc00044c100, 0x20, 0x20, 0xc00044e0e0, 0x6a1262, 0xc0000b76c0
, ...)
-ash: syntax error: unexpected word (expecting ")")
-ash: syntax error: unexpected ")"
root@OpenWrt:~#         github.com/IrineSistiana/mos-chinadns/dispatcher.go:473
+0xa8
-ash: github.com/IrineSistiana/mos-chinadns/dispatcher.go:473: not found
root@OpenWrt:~# main.(*dispatcher).serveRawDNS.func1(0xc0004420b0, 0xc0000a68a0,
 0x91c660, 0xc000450080, 0xc00047a000, 0xc00044c100, 0x20, 0x20, 0xc00044e0e0, 0
xc00047c0c0, ...)
-ash: syntax error: unexpected word (expecting ")")
-ash: syntax error: unexpected ")"
root@OpenWrt:~#         github.com/IrineSistiana/mos-chinadns/dispatcher.go:353
+0xdb
-ash: github.com/IrineSistiana/mos-chinadns/dispatcher.go:353: not found
root@OpenWrt:~# created by main.(*dispatcher).serveRawDNS
-ash: syntax error: unexpected "("
root@OpenWrt:~#         github.com/IrineSistiana/mos-chinadns/dispatcher.go:351
+0x7b3
-ash: github.com/IrineSistiana/mos-chinadns/dispatcher.go:351: not found

**Comment by IrineSistiana** [comment]
@adolink oops...再试试这个，应该没问题了

[mos-chinadns-linux-amd64.zip](https://github.com/IrineSistiana/mos-chinadns/files/4735420/mos-chinadns-linux-amd64.zip)

**Comment by adolink** [comment]
已经能正常工作，没有挂掉，但是不断有类似

WARN[0224] exchange: ioErr: netErr.Timeout: read tcp 106.87.29.133:55082->1.0.0.1:853: i/o timeout  fromUDP="127.0.0.1:1357" id=15343 question="[{live.github.com. 28 1}]"

这样的警告。

**Comment by IrineSistiana** [comment]
> 已经能正常工作，没有挂掉，但是不断有类似
> 
> WARN[0224] exchange: ioErr: netErr.Timeout: read tcp 106.87.29.133:55082->1.0.0.1:853: i/o timeout fromUDP="127.0.0.1:1357" id=15343 question="[{live.github.com. 28 1}]"

正常现象。因某种众所周知的原因，`1.0.0.1`等服务器可能不太稳。
> 
> 这样的警告。
